### ISSUE TITLE
Not possible to edit a submission as a collaborator with full rights

### ISSUE THREAD

**Issue by erikhedman** [NBISweden/fega-sweden-helpdesk-acceptance-testing#28]
**What I tried to do**
We tried to edit metadata objects (Study, Experiment, Analysis) as a collaborator with full rights for a submission in the Submitter Portal (production).

**What I expected to happen**
We expected to see the editing icon to the left when hovering over the row of the metadata object.

**What actually happened**
No editing icon appeared and we could not edit the metadata object.

**Steps to reproduce the result**
1. Invite a collaborator to an ongoing submission and give the collaborator full rights.
2. Ask the collaborator to sign in to the Submitter Portal and edit a metadata object in the submission.

**Screenshots**
No screenshot are available.

**Desktop (please complete the following information):**
 - OS: Windows and Mac
 - Browser: Google Chrome and Safari

**Additional context**
Three different collaborators experienced the same issue. No one could edit the submission.

**Comment by elisavettorstensson** [comment]
I tried this on the test environment (after asking Markus) if it is okay to check in the test environment. Richelle added me as a collaborator in an ongoing submission, and I tried to edit the metadata objects in the submission that she worked with, and I succeeded with this. This issue is fixed now. I will close the issue.
